H = "Nonmetal"
He = "Noble Gas"
Li = "Alkali Metal"
Be = "Alkaline Earth Metal"
B = "Metalloid"
C = "Nonmetal"
N = "Nonmetal"
O = "Nonmetal"
F = "Halogen"
Ne = "Noble Gas"
Na = "Alkali Metal"
Mg = "Alkaline Earth Metal"
Al = "Post-Transition Metal"
Si = "Metalloid"
P = "Nonmetal"
S = "Nonmetal"
Cl = "Halogen"
Ar = "Noble Gas"
K = "Alkali Metal"
Ca = "Alkaline Earth Metal"
Sc = "Transition Metal"
Ti = "Transition Metal"
V = "Transition Metal"
Cr = "Transition Metal"
Mn = "Transition Metal"
Fe = "Transition Metal"
Co = "Transition Metal"
Ni = "Transition Metal"
Cu = "Transition Metal"
Zn = "Transition Metal"
Ga = "Post-Transition Metal"
Ge = "Metalloid"
As = "Metalloid"
Se = "Nonmetal"
Br = "Halogen"
Kr = "Noble Gas"
Rb = "Alkali Metal"
Sr = "Alkaline Earth Metal"
Y = "Transition Metal"
Zr = "Transition Metal"
Nb = "Transition Metal"
Mo = "Transition Metal"
Tc = "Transition Metal"
Ru = "Transition Metal"
Rh = "Transition Metal"
Pd = "Transition Metal"
Ag = "Transition Metal"
Cd = "Transition Metal"
In = "Post-Transition Metal"
Sn = "Post-Transition Metal"
Sb = "Metalloid"
Te = "Metalloid"
I = "Halogen"
Xe = "Noble Gas"
Cs = "Alkali Metal"
Ba = "Alkaline Earth Metal"
La = "Lanthanide"
Ce = "Lanthanide"
Pr = "Lanthanide"
Nd = "Lanthanide"
Pm = "Lanthanide"
Sm = "Lanthanide"
Eu = "Lanthanide"
Gd = "Lanthanide"
Tb = "Lanthanide"
Dy = "Lanthanide"
Ho = "Lanthanide"
Er = "Lanthanide"
Tm = "Lanthanide"
Yb = "Lanthanide"
Lu = "Lanthanide"
Hf = "Transition Metal"
Ta = "Transition Metal"
W = "Transition Metal"
Re = "Transition Metal"
Os = "Transition Metal"
Ir = "Transition Metal"
Pt = "Transition Metal"
Au = "Transition Metal"
Hg = "Transition Metal"
Tl = "Post-Transition Metal"
Pb = "Post-Transition Metal"
Bi = "Post-Transition Metal"
Po = "Metalloid"
At = "Halogen"
Rn = "Noble Gas"
Fr = "Alkali Metal"
Ra = "Alkaline Earth Metal"
Ac = "Actinide"
Th = "Actinide"
Pa = "Actinide"
U = "Actinide"
Np = "Actinide"
Pu = "Actinide"
Am = "Actinide"
Cm = "Actinide"
Bk = "Actinide"
Cf = "Actinide"
Es = "Actinide"
Fm = "Actinide"
Md = "Actinide"
No = "Actinide"
Lr = "Actinide"
Rf = "Transition Metal"
Db = "Transition Metal"
Sg = "Transition Metal"
Bh = "Transition Metal"
Hs = "Transition Metal"
Mt = "Transition Metal"
Ds = "Transition Metal"
Rg = "Transition Metal"
Cn = "Transition Metal"
Nh = "Post-Transition Metal"
Fl = "Post-Transition Metal"
Mc = "Post-Transition Metal"
Lv = "Post-Transition Metal"
Ts = "Halogen"
Og = "Noble Gas"


elist = [
    H, He, Li, Be, B, C, N, O, F, Ne,
    Na, Mg, Al, Si, P, S, Cl, Ar, K, Ca,
    Sc, Ti, V, Cr, Mn, Fe, Co, Ni, Cu, Zn,
    Ga, Ge, As, Se, Br, Kr, Rb, Sr, Y, Zr,
    Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, Sn,
    Sb, Te, I, Xe, Cs, Ba, La, Ce, Pr, Nd,
    Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb,
    Lu, Hf, Ta, W, Re, Os, Ir, Pt, Au, Hg,
    Tl, Pb, Bi, Po, At, Rn, Fr, Ra, Ac, Th,
    Pa, U, Np, Pu, Am, Cm, Bk, Cf, Es, Fm,
    Md, No, Lr, Rf, Db, Sg, Bh, Hs, Mt, Ds,
    Rg, Cn, Nh, Fl, Mc, Lv, Ts, Og
]
