H = "Gas"
He = "Gas"
Li = "Solid"
Be = "Solid"
B = "Solid"
C = "Solid"
N = "Gas"
O = "Gas"
F = "Gas"
Ne = "Gas"
Na = "Solid"
Mg = "Solid"
Al = "Solid"
Si = "Solid"
P = "Solid"
S = "Solid"
Cl = "Gas"
Ar = "Gas"
K = "Solid"
Ca = "Solid"
Sc = "Solid"
Ti = "Solid"
V = "Solid"
Cr = "Solid"
Mn = "Solid"
Fe = "Solid"
Co = "Solid"
Ni = "Solid"
Cu = "Solid"
Zn = "Solid"
Ga = "Solid"
Ge = "Solid"
As = "Solid"
Se = "Solid"
Br = "Liquid"
Kr = "Gas"
Rb = "Solid"
Sr = "Solid"
Y = "Solid"
Zr = "Solid"
Nb = "Solid"
Mo = "Solid"
Tc = "Solid"
Ru = "Solid"
Rh = "Solid"
Pd = "Solid"
Ag = "Solid"
Cd = "Solid"
In = "Solid"
Sn = "Solid"
Sb = "Solid"
Te = "Solid"
I = "Solid"
Xe = "Gas"
Cs = "Solid"
Ba = "Solid"
La = "Solid"
Ce = "Solid"
Pr = "Solid"
Nd = "Solid"
Pm = "Solid"
Sm = "Solid"
Eu = "Solid"
Gd = "Solid"
Tb = "Solid"
Dy = "Solid"
Ho = "Solid"
Er = "Solid"
Tm = "Solid"
Yb = "Solid"
Lu = "Solid"
Hf = "Solid"
Ta = "Solid"
W = "Solid"
Re = "Solid"
Os = "Solid"
Ir = "Solid"
Pt = "Solid"
Au = "Solid"
Hg = "Liquid"
Tl = "Solid"
Pb = "Solid"
Bi = "Solid"
Po = "Solid"
At = "Solid"
Rn = "Gas"
Fr = "Solid"
Ra = "Solid"
Ac = "Solid"
Th = "Solid"
Pa = "Solid"
U = "Solid"
Np = "Solid"
Pu = "Solid"
Am = "Solid"
Cm = "Solid"
Bk = "Solid"
Cf = "Solid"
Es = "Solid"
Fm = "Solid"
Md = "Solid"
No = "Solid"
Lr = "Solid"
Rf = "Solid"
Db = "Solid"
Sg = "Solid"
Bh = "Solid"
Hs = "Solid"
Mt = "Solid"
Ds = "Solid"
Rg = "Solid"
Cn = "Solid"
Nh = "Solid"
Fl = "Solid"
Mc = "Solid"
Lv = "Solid"
Ts = "Solid"
Og = "Gas"


elist = [
    H, He, Li, Be, B, C, N, O, F, Ne,
    Na, Mg, Al, Si, P, S, Cl, Ar, K, Ca,
    Sc, Ti, V, Cr, Mn, Fe, Co, Ni, Cu, Zn,
    Ga, Ge, As, Se, Br, Kr, Rb, Sr, Y, Zr,
    Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, Sn,
    Sb, Te, I, Xe, Cs, Ba, La, Ce, Pr, Nd,
    Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb,
    Lu, Hf, Ta, W, Re, Os, Ir, Pt, Au, Hg,
    Tl, Pb, Bi, Po, At, Rn, Fr, Ra, Ac, Th,
    Pa, U, Np, Pu, Am, Cm, Bk, Cf, Es, Fm,
    Md, No, Lr, Rf, Db, Sg, Bh, Hs, Mt, Ds,
    Rg, Cn, Nh, Fl, Mc, Lv, Ts, Og
]
