# Electron Affinity

H = '0.754 eV'
He = 'N/A'
Li = '0.618 eV'
Be = 'N/A'
B = '0.277 eV'
C = '1.263 eV'
N = 'N/A'
O = '1.461 eV'
F = '3.339 eV'
Ne = 'N/A'
Na = '0.548 eV'
Mg = 'N/A'
Al = '0.441 eV'
Si = '1.385 eV' 
P = '0.746 eV'
S = '2.077 eV'
Cl = '3.617 eV'
Ar = 'N/A'
K = '0.501 eV'
Ca = 'N/A'
Sc = 'N/A'
Ti = '0.079 eV'
V = '0.525 eV'
Cr = '0.666 eV'
Mn = 'N/A'
Fe = '0.163 eV'
Co = '0.661 eV'
Ni = '1.156 eV'
Cu = '1.228 eV'
Zn = 'N/A'
Ga = '0.3 eV'
Ge = '1.35 eV'
As = '0.81 eV'
Se = '2.021 eV'
Br = '3.365 eV'
Kr = 'N/A'
Rb = '0.468 eV'
Sr = 'N/A'
Y = '0.307 eV'
Zr = '0.426 eV'
Nb = '0.893 eV'
Mo = '0.746 eV'
Tc = '0.55 eV'
Ru = '1.05 eV'
Rh = '1.137 eV'
Pd = '0.557 eV'
Ag = '1.302 eV'
Cd = 'N/A'
In = '0.3 eV'
Sn = '1.2 eV'
Sb = '1.07 eV'
Te = '1.971 eV'
I = '3.059 eV'
Xe = 'N/A'
Cs = '0.472 eV'
Ba = 'N/A'
La = '0.5 eV'
Ce = '0.5 eV'
Pr = 'N/A'
Nd = '1.14'
Pm = '0'
Sm = '1.17'
Eu = 'N/A'
Gd = 'N/A'
Tb = 'N/A'
Dy = 'N/A'
Ho = 'N/A'
Er = 'N/A'
Tm = 'N/A'
Yb = 'N/A'
Lu = 'N/A'
Hf = 'N/A'
Ta = '0.322 eV'
W = '0.815 eV'
Re = '0.15 eV'
Os = '1.1 eV'
Ir = '1.565 eV'
Pt = '2.128 eV'
Au = '2.309 eV'
Hg = 'N/A'
Tl = '0.2 eV'
Pb = '0.36 eV'
Bi = '0.946 eV'
Po = '1.9 eV'
At = '2.8 eV'
Rn = 'N/A'
Fr = 'N/A'
Ra = 'N/A'
Ac = 'N/A'
Th = 'N/A'
Pa = 'N/A'
U = 'N/A'
Np = 'N/A'
Pu = 'N/A'
Am = 'N/A'
Cm = 'N/A'
Bk = 'N/A'
Cf = 'N/A'
Es = 'N/A'
Fm = 'N/A'
Md = 'N/A'
No = 'N/A'
Lr = 'N/A'
Rf = 'N/A'
Db = 'N/A'
Sg = 'N/A'
Bh = 'N/A'
Hs = 'N/A'
Mt = 'N/A'
Ds = 'N/A'
Rg = 'N/A'
Cn = 'N/A'
Nh = 'N/A'
Fl = 'N/A'
Mc = 'N/A'
Lv = 'N/A'
Ts = 'N/A'
Og = 'N/A'


elist = [
    H, He, Li, Be, B, C, N, O, F, Ne,
    Na, Mg, Al, Si, P, S, Cl, Ar, K, Ca,
    Sc, Ti, V, Cr, Mn, Fe, Co, Ni, Cu, Zn,
    Ga, Ge, As, Se, Br, Kr, Rb, Sr, Y, Zr,
    Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, Sn,
    Sb, Te, I, Xe, Cs, Ba, La, Ce, Pr, Nd,
    Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb,
    Lu, Hf, Ta, W, Re, Os, Ir, Pt, Au, Hg,
    Tl, Pb, Bi, Po, At, Rn, Fr, Ra, Ac, Th,
    Pa, U, Np, Pu, Am, Cm, Bk, Cf, Es, Fm,
    Md, No, Lr, Rf, Db, Sg, Bh, Hs, Mt, Ds,
    Rg, Cn, Nh, Fl, Mc, Lv, Ts, Og
]
